services:
  - type: web
    name: my-app-name # the name of this service, you should change this
    runtime: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
